#import "AppDelegate.h"
#import <Firebase/Firebase.h>

#import <React/RCTBundleURLProvider.h>
#import <React/RCTLinkingManager.h>

// CRITICAL: Import ExpoModulesCore Swift header BEFORE AppPlatform-Swift.h
// AppPlatform-Swift.h exposes ExpoModulesProvider which extends ModulesProvider (a Swift class).
// The @import ExpoModulesCore in the generated header only imports ObjC headers, not Swift.
// This import makes ModulesProvider visible to the ObjC compiler.
#import "ExpoModulesCore-Swift.h"

// CoreBluetooth must be imported before AppPlatform-Swift.h because the generated header
// exposes TrakPlusBLECore's CBPeripheralDelegate and CBCentralManagerDelegate conformances.
#import <CoreBluetooth/CoreBluetooth.h>

// Import Swift classes for factory reset and BLE
// This header is auto-generated by Xcode when Swift code exists in the project
#import "AppPlatform-Swift.h"

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  // =========================================================================
  // REINSTALL DETECTION + FACTORY RESET
  // =========================================================================
  // CRITICAL: This MUST run BEFORE Firebase, React Native, or any other init.
  //
  // WHY: iOS Keychain survives app uninstall. If user reinstalls the app,
  // stale Keychain tokens can cause crashes. This detects reinstall and
  // wipes all persistent state to ensure a clean start.
  //
  // DETECTION: Keychain marker exists + sandbox sentinel file missing = REINSTALL
  // =========================================================================

  if ([ReinstallDetector checkForReinstall]) {
    NSLog(@"[AppDelegate] REINSTALL DETECTED - initiating factory reset");

    if ([FactoryResetGuard shouldAllowReset]) {
      // Increment attempt counter BEFORE wipe (in case wipe crashes)
      [FactoryResetGuard incrementAttempt];

      // Perform factory reset in order: Keychain -> SQLite -> AsyncStorage
      // NOTE: Swift classes are exported to ObjC via @objc() annotations:
      // - KeychainWipeModule.swift → @objc(KeychainWipe)
      // - FactoryResetModule.swift → @objc(FactoryReset)
      BOOL keychainWiped = [KeychainWipe wipeAllKeychainItems];
      BOOL dbWiped = [FactoryReset wipeSQLiteDatabase];
      BOOL asyncStorageWiped = [FactoryReset wipeAsyncStorage];

      NSLog(@"[AppDelegate] Factory reset results - Keychain:%d, SQLite:%d, AsyncStorage:%d",
            keychainWiped, dbWiped, asyncStorageWiped);

      if (keychainWiped && dbWiped && asyncStorageWiped) {
        // Mark reset complete (creates sentinel + Keychain marker)
        [FactoryResetGuard markResetComplete];
        NSLog(@"[AppDelegate] Factory reset completed successfully");
      } else {
        // PARTIAL FAILURE: Do NOT mark reset complete, but RE-SEED the Keychain marker.
        //
        // CRITICAL INSIGHT:
        // The Keychain wipe (if it succeeded) deleted the install marker. Without re-seeding:
        // - Next launch sees: marker=NO, sentinel=NO → "FRESH INSTALL" → NO RETRY!
        // - The corrupt state persists because we don't detect it as a reinstall.
        //
        // By re-seeding the marker while leaving sentinel absent:
        // - Next launch sees: marker=YES, sentinel=NO → "REINSTALL DETECTED" → RETRY!
        // - FactoryResetGuard.shouldAllowReset() limits retries (guard incremented above).
        // - After max attempts, shouldAllowReset() returns false and we skip gracefully.
        //
        // This ensures partial failure leads to bounded retries, not silent acceptance.
        NSLog(@"[AppDelegate] Factory reset PARTIALLY FAILED - re-seeding marker for retry");
        NSLog(@"[AppDelegate] Wipe results: Keychain=%d, SQLite=%d, AsyncStorage=%d",
              keychainWiped, dbWiped, asyncStorageWiped);

        // Re-seed the Keychain marker so next launch detects reinstall.
        //
        // CRITICAL: Use hasKeychainMarker() to check ACTUAL marker presence, not keychainWiped.
        //
        // WHY: wipeAllKeychainItems() processes classes in order:
        //   1. GenericPassword (contains the install marker)
        //   2. InternetPassword
        //   3. Certificate, Key, Identity
        //
        // If GenericPassword succeeds (deleting the marker) but a later class fails,
        // keychainWiped returns false even though the marker is gone. Gating on
        // keychainWiped would skip re-seeding, causing:
        //   marker=NO, sentinel=NO → "FRESH INSTALL" → NO RETRY!
        //
        // By checking actual marker presence, we always re-seed when needed.
        if (![ReinstallDetector hasKeychainMarker]) {
          NSLog(@"[AppDelegate] Marker is absent (may have been wiped) - re-seeding for retry");
          BOOL markerReseeded = [ReinstallDetector setKeychainMarker];
          if (markerReseeded) {
            NSLog(@"[AppDelegate] Marker re-seeded successfully - next launch will retry reset");
          } else {
            NSLog(@"[AppDelegate] WARNING: Failed to re-seed marker - retry may not trigger");
          }
        } else {
          // Marker still exists (Keychain wipe failed before reaching GenericPassword)
          NSLog(@"[AppDelegate] Marker still exists - retry will trigger naturally");
        }

        NSLog(@"[AppDelegate] Guard will allow retry at next launch (up to max attempts per build)");
      }
    } else {
      NSLog(@"[AppDelegate] Factory reset BLOCKED - max attempts exceeded for this build");
    }
  } else {
    // Not a reinstall - ensure both markers exist for future detection
    NSString *sentinelPath = [ReinstallDetector getSentinelPath];
    BOOL sentinelExists = [[NSFileManager defaultManager] fileExistsAtPath:sentinelPath];
    BOOL keychainMarkerExists = [ReinstallDetector hasKeychainMarker];

    if (!sentinelExists) {
      // Fresh install case - create both markers
      NSLog(@"[AppDelegate] Fresh install detected - creating markers");
      [ReinstallDetector createSentinelFile];
      [ReinstallDetector setKeychainMarker];
    } else if (!keychainMarkerExists) {
      // SELF-HEALING: Sentinel exists but keychain marker is missing.
      // This can happen if:
      // - Keychain was cleared externally (rare)
      // - Previous marker creation failed
      // - Keychain access temporarily restricted
      //
      // Without re-seeding, future reinstalls won't be detected because:
      // 1. User continues using app (other Keychain items accumulate)
      // 2. User uninstalls → sentinel deleted, Keychain items persist (but no marker)
      // 3. User reinstalls → neither marker nor sentinel exists → FRESH INSTALL
      // 4. Stale Keychain items (OAuth tokens, etc.) could cause crashes
      NSLog(@"[AppDelegate] SELF-HEALING: Sentinel exists but keychain marker missing - re-seeding marker");
      [ReinstallDetector setKeychainMarker];
    }
  }

  // =========================================================================
  // END REINSTALL DETECTION
  // =========================================================================

  // =========================================================================
  // BLE EARLY INITIALIZATION FOR COREBLUETOOTH RESTORATION
  // =========================================================================
  // MUST run before React Native bridge startup so iOS can deliver
  // centralManager:willRestoreState: to the BLE singleton.
  [TrakPlusBLEInitializer initializeBLECore];

// @generated begin @react-native-firebase/app-didFinishLaunchingWithOptions - expo prebuild (DO NOT MODIFY) sync-ecd111c37e49fdd1ed6354203cd6b1e2a38cccda
[FIRApp configure];
// @generated end @react-native-firebase/app-didFinishLaunchingWithOptions

  // =========================================================================
  // HEALTHKIT BACKGROUND DELIVERY — OBSERVER REGISTRATION
  // =========================================================================
  // CRITICAL: HKObserverQuery MUST be registered BEFORE applicationDidFinishLaunchingWithOptions returns.
  // iOS wakes the app briefly when HealthKit data changes; without early registration,
  // background delivery is silently never delivered.
  //
  // The observer internally guards on HKHealthStore.isHealthDataAvailable()
  // so this is a safe no-op on iPads or simulators without HealthKit.
  //
  // @see HealthKitObserver.swift (registerDefaultObservers)
  // @see AppPlatform.entitlements (com.apple.developer.healthkit.background-delivery = true)
  // =========================================================================
  [[HealthKitObserver shared] registerDefaultObservers];

  self.moduleName = @"main";

  // You can add your custom initial props in the dictionary below.
  // They will be passed down to the ViewController used by React Native.
  self.initialProps = @{};

  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
  return [self bundleURL];
}

- (NSURL *)bundleURL
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@".expo/.virtual-metro-entry"];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

// Linking API
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
  return [super application:application openURL:url options:options] || [RCTLinkingManager application:application openURL:url options:options];
}

// Universal Links
- (BOOL)application:(UIApplication *)application continueUserActivity:(nonnull NSUserActivity *)userActivity restorationHandler:(nonnull void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler {
  BOOL result = [RCTLinkingManager application:application continueUserActivity:userActivity restorationHandler:restorationHandler];
  return [super application:application continueUserActivity:userActivity restorationHandler:restorationHandler] || result;
}

// Explicitly define remote notification delegates to ensure compatibility with some third-party libraries
- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken
{
  return [super application:application didRegisterForRemoteNotificationsWithDeviceToken:deviceToken];
}

// Explicitly define remote notification delegates to ensure compatibility with some third-party libraries
- (void)application:(UIApplication *)application didFailToRegisterForRemoteNotificationsWithError:(NSError *)error
{
  return [super application:application didFailToRegisterForRemoteNotificationsWithError:error];
}

// Explicitly define remote notification delegates to ensure compatibility with some third-party libraries
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler
{
  return [super application:application didReceiveRemoteNotification:userInfo fetchCompletionHandler:completionHandler];
}

@end
