import { sqliteTable, text, integer, real, primaryKey, unique, uniqueIndex, index } from 'drizzle-orm/sqlite-core';
import { sql } from 'drizzle-orm';
export const users = sqliteTable('users', {
  id: text('id').primaryKey().notNull(),
  email: text('email').notNull().unique(),
  username: text('username').notNull().unique(),
  cognitoId: text('cognito_id').unique(),
  displayName: text('display_name'),
  avatarUrl: text('avatar_url'),
  bio: text('bio'),
  dateOfBirth: text('date_of_birth'),
  location: text('location'), 
  preferences: text('preferences').default('{}'), 
  notificationSettings: text('notification_settings').default('{}'), 
  privacySettings: text('privacy_settings').default('{}'), 
  accountStatus: text('account_status').default('active'),
  emailVerified: integer('email_verified', { mode: 'boolean' }).default(false),
  phoneVerified: integer('phone_verified', { mode: 'boolean' }).default(false),
  subscriptionTier: text('subscription_tier').default('free'),
  subscriptionExpires: text('subscription_expires'),
  createdAt: text('created_at').default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text('updated_at').default(sql`CURRENT_TIMESTAMP`),
  lastLoginAt: text('last_login_at'),
  deletedAt: text('deleted_at'),
}, (table) => [
  index('idx_users_email').on(table.email),
  index('idx_users_username').on(table.username),
  index('idx_users_cognito_id').on(table.cognitoId),
]);
export const devices = sqliteTable('devices', {
  id: text('id').primaryKey().notNull(),
  userId: text('user_id').notNull(),
  deviceName: text('device_name').notNull(),
  deviceType: text('device_type').default('OTHER'),
  model: text('model'),
  serialNumber: text('serial_number'),
  macAddress: text('mac_address').unique(),
  firmwareVersion: text('firmware_version'),
  hardwareVersion: text('hardware_version'),
  settings: text('settings').default('{}'), 
  lastCalibrated: text('last_calibrated'),
  calibrationData: text('calibration_data'), 
  requiresCalibration: integer('requires_calibration', { mode: 'boolean' }).default(false),
  isPaired: integer('is_paired', { mode: 'boolean' }).default(false),
  isActive: integer('is_active', { mode: 'boolean' }).default(true),
  lastConnected: text('last_connected'),
  batteryLevel: integer('battery_level'),
  totalSessions: integer('total_sessions').default(0),
  totalDurationMs: integer('total_duration_ms').default(0),
  lastUsed: text('last_used'),
  pairedAt: text('paired_at'),
  createdAt: text('created_at').default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text('updated_at').default(sql`CURRENT_TIMESTAMP`),
  serverId: text('server_id'),
  data: text('data'), 
  syncStatus: text('sync_status').default('pending'),
  lastSyncedAt: text('last_synced_at'),
  deletedAt: text('deleted_at'),
  version: integer('version').default(1), 
  syncError: text('sync_error'),
  status: text('status').default('ACTIVE'),
  type: text('type').default('OTHER'),
  bluetoothId: text('bluetooth_id').unique(),
  specifications: text('specifications'), 
  brand: text('brand'),
  lastSeen: text('last_seen'),
}, (table) => [
  index('idx_devices_user_id').on(table.userId),
  index('idx_devices_mac_address').on(table.macAddress),
  index('idx_devices_type').on(table.type),
  index('idx_devices_server_id').on(table.serverId),
  index('idx_devices_sync_status').on(table.syncStatus),
  index('idx_devices_deleted_at').on(table.deletedAt),
  index('idx_devices_serial_number').on(table.serialNumber),
  index('idx_devices_bluetooth_id').on(table.bluetoothId),
  index('idx_devices_status').on(table.status),
  index('idx_devices_is_active').on(table.isActive),
  index('idx_devices_last_seen').on(table.lastSeen),
]);
export const sessions = sqliteTable('sessions', {
  id: text('id').primaryKey().notNull(),
  userId: text('userId').notNull(),
  purchaseId: text('purchaseId'),
  deviceId: text('deviceId'),
  clientSessionId: text('clientSessionId'),
  primaryProductId: text('primaryProductId'),
  sessionStartTimestamp: text('sessionStartTimestamp').notNull(),
  sessionEndTimestamp: text('sessionEndTimestamp'), 
  hitCount: integer('hitCount').default(0),
  totalDurationMs: integer('totalDurationMs').default(0),
  avgHitDurationMs: real('avgHitDurationMs').default(0),
  sessionTypeHeuristic: text('sessionTypeHeuristic'),
  observationFeature: real('observationFeature'),
  version: integer('version').default(1),
  createdAt: text('createdAt').default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text('updatedAt').default(sql`CURRENT_TIMESTAMP`),
  syncStatus: text('sync_status').default('pending'),
  syncVersion: integer('sync_version').default(1),
  status: text('status').default('ACTIVE'), 
  clientId: text('client_id'),
  notes: text('notes'),
}, (table) => [
  index('idx_sessions_user_id').on(table.userId),
  index('idx_sessions_start_time').on(table.sessionStartTimestamp),
  index('idx_sessions_status').on(table.status),
  index('idx_sessions_user_date').on(table.userId, table.sessionStartTimestamp),
  index('idx_sessions_sync_status').on(table.syncStatus),
  index('idx_sessions_user_status').on(table.userId, table.status),
  index('idx_sessions_client_id').on(table.clientId),
]);
export const cursorState = sqliteTable('cursor_state', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  entityType: text('entity_type').notNull().unique(),
  cursorValue: text('cursor_value'),
  lastSyncTimestamp: text('last_sync_timestamp').notNull().default(sql`(datetime('now'))`),
  recordsSynced: integer('records_synced').notNull().default(0),
  hasMore: integer('has_more', { mode: 'boolean' }).notNull().default(false),
  syncStatus: text('sync_status').notNull().default('idle'), 
  errorMessage: text('error_message'),
  createdAt: text('created_at').notNull().default(sql`(datetime('now'))`),
  updatedAt: text('updated_at').notNull().default(sql`(datetime('now'))`),
}, (table) => [
  index('idx_cursor_state_entity_type').on(table.entityType),
  index('idx_cursor_state_sync_status').on(table.syncStatus),
]);
export const tombstones = sqliteTable('tombstones', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  userId: text('user_id'),
  entityType: text('entity_type').notNull(),
  entityId: text('entity_id').notNull(),
  serverId: text('server_id'),
  deletedAt: text('deleted_at').notNull().default(sql`(datetime('now'))`),
  syncStatus: text('sync_status').notNull().default('pending'),
  syncedAt: text('synced_at'),
  errorMessage: text('error_message'),
  metadata: text('metadata'), 
  createdAt: text('created_at').notNull().default(sql`(datetime('now'))`),
}, (table) => [
  unique().on(table.entityType, table.entityId),
  index('idx_tombstones_entity_type_id').on(table.entityType, table.entityId),
  index('idx_tombstones_sync_status').on(table.syncStatus),
  index('idx_tombstones_deleted_at').on(table.deletedAt),
  index('idx_tombstones_user_status').on(table.userId, table.syncStatus),
]);
export const outboxEvents = sqliteTable('outbox_events', {
  id: text('id').primaryKey().notNull(),
  userId: text('user_id').notNull(),
  aggregateId: text('aggregate_id').notNull(),
  aggregateType: text('aggregate_type').notNull(),
  eventType: text('event_type').notNull(),
  payload: text('payload').notNull(), 
  status: text('status').default('PENDING'), 
  retryCount: integer('retry_count').default(0),
  maxRetries: integer('max_retries').default(3),
  processedAt: text('processed_at'),
  error: text('error'),
  createdAt: text('created_at').default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text('updated_at').default(sql`CURRENT_TIMESTAMP`),
  lastRetryAt: text('last_retry_at'),
  errorDetails: text('error_details'),
}, (table) => [
  index('idx_outbox_events_status').on(table.status),
  index('idx_outbox_events_aggregate').on(table.aggregateType, table.aggregateId),
  index('idx_outbox_events_user_status').on(table.userId, table.status),
]);
export const syncOperations = sqliteTable('sync_operations', {
  id: text('id').primaryKey().notNull(),
  userId: text('user_id').notNull(),
  syncType: text('sync_type').notNull(), 
  status: text('status').notNull(), 
  startedAt: text('started_at').notNull(),
  completedAt: text('completed_at'),
  entitiesSynced: text('entities_synced'), 
  changesPushed: integer('changes_pushed').default(0),
  changesPulled: integer('changes_pulled').default(0),
  conflictsDetected: integer('conflicts_detected').default(0),
  errorMessage: text('error_message'),
  clientVersion: text('client_version'),
  serverVersion: text('server_version'),
  correlationId: text('correlation_id'),
  createdAt: text('created_at').default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text('updated_at').default(sql`CURRENT_TIMESTAMP`),
}, (table) => [
  index('idx_sync_operations_user_id').on(table.userId),
  index('idx_sync_operations_status').on(table.status),
]);
export const idMap = sqliteTable('id_map', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  entityType: text('entity_type').notNull(),
  clientId: text('client_id').notNull(),
  serverId: text('server_id'),
  status: text('status').default('pending'), 
  syncedAt: text('synced_at'),
  createdAt: text('created_at').default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text('updated_at').default(sql`CURRENT_TIMESTAMP`),
}, (table) => [
  unique().on(table.entityType, table.clientId),
  index('idx_id_map_entity_client').on(table.entityType, table.clientId),
  index('idx_id_map_entity_server').on(table.entityType, table.serverId),
]);
export const syncMetadata = sqliteTable('sync_metadata', {
  id: text('id').primaryKey(),
  tableName: text('table_name').notNull(),
  localId: text('local_id').notNull(),
  serverId: text('server_id'),
  syncStatus: text('sync_status').notNull().default('pending'),
  lastModified: integer('last_modified').notNull(),
  conflictData: text('conflict_data'),
  errorMessage: text('error_message'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
}, (table) => [
  unique().on(table.tableName, table.localId),
  index('idx_sync_metadata_status').on(table.syncStatus),
  index('idx_sync_metadata_table_local').on(table.tableName, table.localId),
  index('idx_sync_metadata_server_id').on(table.serverId),
]);
export const healthSources = sqliteTable('health_sources', {
  id: text('id').primaryKey().notNull(),
  userId: text('user_id').notNull(),
  platform: text('platform').notNull(), 
  sourceAppId: text('source_app_id').notNull(), 
  deviceId: text('device_id').notNull().default('__NO_DEVICE__'),
  sourceName: text('source_name'),
  hardwareId: text('hardware_id'),
  isActive: integer('is_active', { mode: 'boolean' }).default(true),
  lastSyncAt: integer('last_sync_at'),
  serverId: text('server_id'),
  createdAt: integer('created_at').default(sql`(strftime('%s','now')*1000)`),
  updatedAt: integer('updated_at').default(sql`(strftime('%s','now')*1000)`),
}, (table) => [
  unique('uq_health_sources_key').on(table.userId, table.platform, table.sourceAppId, table.deviceId),
  index('idx_health_sources_user_platform').on(table.userId, table.platform),
  index('idx_health_sources_user_id').on(table.userId),
]);
export const healthSamples = sqliteTable('health_samples', {
  id: text('id').primaryKey().notNull(),
  userId: text('user_id').notNull(),
  sourceId: text('source_id').notNull(),
  sourceRecordId: text('source_record_id').notNull(),
  sampleType: text('sample_type').notNull(), 
  valueKind: text('value_kind').notNull(),
  startTimestamp: integer('start_timestamp').notNull(),
  endTimestamp: integer('end_timestamp').notNull(),
  durationSeconds: integer('duration_seconds'),
  deviceId: text('device_id'),
  externalUuid: text('external_uuid'),
  value: real('value'),
  unit: text('unit'),
  categoryCode: text('category_code'), 
  metadata: text('metadata'), 
  uploadStatus: text('upload_status').default('pending'), 
  stagedBatchId: text('staged_batch_id'),
  uploadRequestId: text('upload_request_id'), 
  uploadedAt: integer('uploaded_at'),
  uploadError: text('upload_error'),
  uploadAttemptCount: integer('upload_attempt_count').notNull().default(0),
  nextUploadAttemptAt: integer('next_upload_attempt_at'),
  stateUpdatedAtMs: integer('state_updated_at_ms'), 
  isDeleted: integer('is_deleted', { mode: 'boolean' }).default(false),
  deletedAtMs: integer('deleted_at_ms'),
  createdAt: integer('created_at').default(sql`(strftime('%s','now')*1000)`),
}, (table) => [
  index('idx_health_samples_user_type_time').on(table.userId, table.sampleType, table.startTimestamp),
  index('idx_health_samples_upload_status').on(table.uploadStatus),
  index('idx_health_samples_staged_batch').on(table.stagedBatchId),
  index('idx_health_samples_source_record').on(table.userId, table.sourceId, table.sourceRecordId, table.startTimestamp),
  unique('uq_health_samples_source_record').on(table.userId, table.sourceId, table.sourceRecordId, table.startTimestamp),
  index('idx_health_samples_retry').on(table.userId, table.uploadStatus, table.nextUploadAttemptAt),
  index('idx_health_samples_state_recovery').on(table.userId, table.uploadStatus, table.stateUpdatedAtMs),
  index('idx_health_samples_user_deleted').on(table.userId, table.isDeleted),
  index('idx_health_samples_deleted_at').on(table.deletedAtMs),
  index('idx_health_samples_retention_purge').on(table.userId, table.uploadStatus, table.uploadedAt),
  index('idx_health_samples_deleted_purge').on(table.userId, table.isDeleted, table.deletedAtMs),
]);
export const healthIngestCursors = sqliteTable('health_ingest_cursors', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  userId: text('user_id').notNull(),
  sourceId: text('source_id').notNull(),
  sampleType: text('sample_type').notNull(),
  scope: text('scope').notNull().default('change_anchor'), 
  anchorData: text('anchor_data'), 
  cursorVersion: integer('cursor_version').notNull().default(1), 
  lastIngestTimestamp: integer('last_ingest_timestamp'),
  totalSamplesIngested: integer('total_samples_ingested').default(0),
  coldBackfillEndTs: integer('cold_backfill_end_ts'),
  coldBackfillStartTs: integer('cold_backfill_start_ts'),
  coldPageFromTs: integer('cold_page_from_ts'), 
  lastSyncAt: integer('last_sync_at'),
  createdAt: integer('created_at').default(sql`(strftime('%s','now')*1000)`),
  updatedAt: integer('updated_at').default(sql`(strftime('%s','now')*1000)`),
}, (table) => [
  unique('uq_health_ingest_cursor').on(table.userId, table.sourceId, table.sampleType, table.scope),
  index('idx_health_ingest_cursors_lookup').on(table.userId, table.sourceId, table.sampleType, table.scope),
]);
export const healthSampleDeletionQueue = sqliteTable('health_sample_deletion_queue', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  userId: text('user_id').notNull(),
  sourceId: text('source_id').notNull(),
  sourceRecordId: text('source_record_id').notNull(),
  startTimestampMs: integer('start_timestamp_ms'), 
  deletedAtMs: integer('deleted_at_ms').notNull(),
  uploadStatus: text('upload_status').default('pending'),
  uploadedAt: integer('uploaded_at'),
  uploadError: text('upload_error'),
  uploadAttemptCount: integer('upload_attempt_count').notNull().default(0),
  nextUploadAttemptAt: integer('next_upload_attempt_at'),
  stateUpdatedAtMs: integer('state_updated_at_ms'),
  stagedBatchId: text('staged_batch_id'),
  uploadRequestId: text('upload_request_id'),
  createdAt: integer('created_at').default(sql`(strftime('%s','now')*1000)`),
}, (table) => [
  unique('uq_deletion_queue_sample').on(table.userId, table.sourceId, table.sourceRecordId, table.startTimestampMs),
  index('idx_deletion_queue_pending').on(table.userId, table.uploadStatus),
  index('idx_deletion_queue_retry').on(table.uploadStatus, table.nextUploadAttemptAt),
  index('idx_deletion_queue_state_recovery').on(table.uploadStatus, table.stateUpdatedAtMs),
  index('idx_deletion_queue_batch').on(table.stagedBatchId),
]);
export const localHealthRollupDay = sqliteTable('local_health_rollup_day', {
  id: text('id').primaryKey().notNull(),
  userId: text('user_id').notNull(),
  metricCode: text('metric_code').notNull(),
  dayUtc: text('day_utc').notNull(), 
  valueKind: text('value_kind').notNull(),
  sumVal: real('sum_val'),
  countVal: integer('count_val').notNull().default(0),
  minVal: real('min_val'),
  maxVal: real('max_val'),
  avgVal: real('avg_val'),
  timezoneOffsetMin: integer('timezone_offset_min'),
  freshnessStatus: text('freshness_status').notNull().default('NO_DATA'),
  computedAtIso: text('computed_at_iso'),
  sourceWatermark: text('source_watermark').notNull().default('0'), 
  computeVersion: integer('compute_version').notNull().default(1),
  dataQuality: text('data_quality').notNull().default('FULL'),
  fetchedAt: integer('fetched_at'),
  createdAt: integer('created_at').default(sql`(strftime('%s','now')*1000)`),
  updatedAt: integer('updated_at').default(sql`(strftime('%s','now')*1000)`),
}, (table) => [
  unique('uq_local_rollup_natural_key').on(table.userId, table.metricCode, table.dayUtc),
  index('idx_local_rollup_lookup').on(table.userId, table.metricCode, table.dayUtc),
  index('idx_local_rollup_status').on(table.userId, table.freshnessStatus),
]);
export const localSleepNightSummary = sqliteTable('local_sleep_night_summary', {
  id: text('id').primaryKey().notNull(),
  userId: text('user_id').notNull(),
  nightLocalDate: text('night_local_date').notNull(), 
  timezoneOffsetMin: integer('timezone_offset_min').notNull(),
  sleepStartTs: text('sleep_start_ts'),
  sleepEndTs: text('sleep_end_ts'),
  inBedStartTs: text('in_bed_start_ts'),
  inBedEndTs: text('in_bed_end_ts'),
  totalSleepMin: integer('total_sleep_min'),
  inBedMin: integer('in_bed_min'),
  awakeMin: integer('awake_min'),
  remMin: integer('rem_min'),
  deepMin: integer('deep_min'),
  lightMin: integer('light_min'),
  sleepEfficiency: real('sleep_efficiency'),
  wakeEvents: integer('wake_events'),
  sleepLatencyMin: integer('sleep_latency_min'),
  hadSessionBefore: integer('had_session_before', { mode: 'boolean' }).notNull().default(false),
  sessionIdBefore: text('session_id_before'),
  hoursBeforeBed: real('hours_before_bed'),
  hasRemData: integer('has_rem_data', { mode: 'boolean' }).notNull().default(false),
  hasDeepData: integer('has_deep_data', { mode: 'boolean' }).notNull().default(false),
  hasLightData: integer('has_light_data', { mode: 'boolean' }).notNull().default(false),
  hasAwakeData: integer('has_awake_data', { mode: 'boolean' }).notNull().default(false),
  canonicalSourceId: text('canonical_source_id'),
  sourceCount: integer('source_count').notNull().default(1),
  sourceCoverage: real('source_coverage'),
  dataQualityScore: real('data_quality_score'),
  freshnessStatus: text('freshness_status').notNull().default('NO_DATA'),
  computedAtIso: text('computed_at_iso'),
  sourceWatermark: text('source_watermark').notNull().default('0'),
  computeVersion: integer('compute_version').notNull().default(1),
  dataQuality: text('data_quality').notNull().default('FULL'),
  fetchedAt: integer('fetched_at'),
  createdAt: integer('created_at').default(sql`(strftime('%s','now')*1000)`),
  updatedAt: integer('updated_at').default(sql`(strftime('%s','now')*1000)`),
}, (table) => [
  unique('uq_local_sleep_natural_key').on(table.userId, table.nightLocalDate),
  index('idx_local_sleep_lookup').on(table.userId, table.nightLocalDate),
  index('idx_local_sleep_status').on(table.userId, table.freshnessStatus),
]);
export const localSessionImpactSummary = sqliteTable('local_session_impact_summary', {
  id: text('id').primaryKey().notNull(),
  sessionId: text('session_id').notNull(),
  userId: text('user_id').notNull(),
  metricCode: text('metric_code').notNull(),
  windowMinutes: integer('window_minutes').notNull().default(60),
  resolution: text('resolution').notNull().default('1min'),
  avgBefore: real('avg_before'),
  minBefore: real('min_before'),
  maxBefore: real('max_before'),
  countBefore: integer('count_before').notNull().default(0),
  avgDuring: real('avg_during'),
  minDuring: real('min_during'),
  maxDuring: real('max_during'),
  countDuring: integer('count_during').notNull().default(0),
  avgAfter: real('avg_after'),
  minAfter: real('min_after'),
  maxAfter: real('max_after'),
  countAfter: integer('count_after').notNull().default(0),
  deltaDuringAbs: real('delta_during_abs'),
  deltaDuringPct: real('delta_during_pct'),
  deltaAfterAbs: real('delta_after_abs'),
  deltaAfterPct: real('delta_after_pct'),
  beforeCoverage: real('before_coverage'),
  duringCoverage: real('during_coverage'),
  afterCoverage: real('after_coverage'),
  hasSignificantGaps: integer('has_significant_gaps', { mode: 'boolean' }).notNull().default(false),
  isReliable: integer('is_reliable', { mode: 'boolean' }).notNull().default(true),
  freshnessStatus: text('freshness_status').notNull().default('NO_DATA'),
  computedAtIso: text('computed_at_iso'),
  sourceWatermark: text('source_watermark').notNull().default('0'),
  computeVersion: integer('compute_version').notNull().default(1),
  dataQuality: text('data_quality').notNull().default('FULL'),
  fetchedAt: integer('fetched_at'),
  createdAt: integer('created_at').default(sql`(strftime('%s','now')*1000)`),
  updatedAt: integer('updated_at').default(sql`(strftime('%s','now')*1000)`),
}, (table) => [
  unique('uq_local_impact_natural_key').on(table.sessionId, table.metricCode, table.windowMinutes, table.resolution),
  index('idx_local_impact_session').on(table.userId, table.sessionId),
  index('idx_local_impact_status').on(table.userId, table.freshnessStatus),
]);
export const localRollupDirtyKeys = sqliteTable('local_rollup_dirty_keys', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  userId: text('user_id').notNull(),
  metricCode: text('metric_code').notNull(),
  dayUtc: text('day_utc').notNull(),
  reason: text('reason').notNull(), 
  enqueuedAt: integer('enqueued_at').notNull(),
}, (table) => [
  unique('uq_rollup_dirty_key').on(table.userId, table.metricCode, table.dayUtc),
  index('idx_rollup_dirty_dequeue').on(table.userId, table.enqueuedAt),
]);
export const localSleepDirtyNights = sqliteTable('local_sleep_dirty_nights', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  userId: text('user_id').notNull(),
  nightLocalDate: text('night_local_date').notNull(),
  reason: text('reason').notNull(),
  enqueuedAt: integer('enqueued_at').notNull(),
}, (table) => [
  unique('uq_sleep_dirty_night').on(table.userId, table.nightLocalDate),
  index('idx_sleep_dirty_dequeue').on(table.userId, table.enqueuedAt),
]);
export type DbUser = typeof users.$inferSelect;
export type DbDevice = typeof devices.$inferSelect;
export type DbSession = typeof sessions.$inferSelect;
export type DbCursorState = typeof cursorState.$inferSelect;
export type DbTombstone = typeof tombstones.$inferSelect;
export type DbOutboxEvent = typeof outboxEvents.$inferSelect;
export type DbSyncOperation = typeof syncOperations.$inferSelect;
export type DbIdMap = typeof idMap.$inferSelect;
export type DbSyncMetadata = typeof syncMetadata.$inferSelect;
export type DbHealthSource = typeof healthSources.$inferSelect;
export type DbHealthSample = typeof healthSamples.$inferSelect;
export type DbHealthIngestCursor = typeof healthIngestCursors.$inferSelect;
export type DbHealthSampleDeletionQueue = typeof healthSampleDeletionQueue.$inferSelect;
export type DbLocalHealthRollupDay = typeof localHealthRollupDay.$inferSelect;
export type DbLocalSleepNightSummary = typeof localSleepNightSummary.$inferSelect;
export type DbLocalSessionImpactSummary = typeof localSessionImpactSummary.$inferSelect;
export type DbLocalRollupDirtyKey = typeof localRollupDirtyKeys.$inferSelect;
export type DbLocalSleepDirtyNight = typeof localSleepDirtyNights.$inferSelect;
export type DbUserInsert = typeof users.$inferInsert;
export type DbDeviceInsert = typeof devices.$inferInsert;
export type DbSessionInsert = typeof sessions.$inferInsert;
export type DbOutboxEventInsert = typeof outboxEvents.$inferInsert;
export type DbTombstoneInsert = typeof tombstones.$inferInsert;
export type DbHealthSampleInsert = typeof healthSamples.$inferInsert;
export type DbHealthSourceInsert = typeof healthSources.$inferInsert;
