export * from './types';
export { calculateCRC16, verifyCRC16, extractCRC16, appendCRC16 } from './crc16';
export {
  getNextSequenceNumber,
  resetSequenceCounter,
  buildFrame,
  buildSimpleMessage,
  buildHelloMessage,
  buildAckMessage,
  buildNackMessage,
  buildTimeSyncMessage,
  buildSyncRequestMessage,
  buildSetConfigMessage,
  buildSetSensitivityMessage,
  buildGetConfigMessage,
  buildClearBondsMessage,
  buildPairingModeMessage,
  buildSetWifiConfigMessage,
  WIFI_MAX_SSID_LEN,
  WIFI_MAX_PASS_LEN,
  buildEnterOtaModeMessage,
  parseFrame,
  parseHitEvent,
  parseBatteryStatus,
  parseHelloAck,
  parseCalibrationResult,
  parseAckPayload,
  parseNackPayload,
  parseConfigData,
  parseDeviceStatus,
  getMessageTypeName,
  getErrorCodeName,
  toHexString,
  base64ToUint8Array,
  uint8ArrayToBase64,
} from './BinaryProtocol';
